### ISSUE TITLE
Update the springboot version

### ISSUE THREAD

**Issue by yixingjia** [vmware/flowgate#423]
We need to update the springboot version as the current version is going to out off support soon.

**Comment by Pengpengwanga** [comment]
1>AssetController,AssetService,AssetControllerTest,PreDefineDataLoader
2>AuthController,AuthControllerTest,FacilityController,FacilityControllerTest,SDDCController,SDDCControllerTest,SensorSettingController,SensorSettingControllerTest,SystemSummaryTest
