### ISSUE TITLE
Dynamically calculate the item number of predefined data in database start up script.

### ISSUE THREAD

**Issue by yixingjia** [vmware/flowgate#509]
Currently we use 
if [ -n "$DATACOUNT" ] && [ ${DATACOUNT#*:} = "95" ];then
in make/database/init.sh  
to check whether the database has been successfully initialized. Each time we add new data items we need to change the number. we should dynamically calculate the items number instead of hardcode.

**Comment by VMware-HaoyuLi** [comment]
Fix By #511
